spring:
  application:
    name: bankserver

  datasource:
    generate-unique-name: false
    name: bankserverdb
    url: jdbc:postgresql://localhost:5432/bankserverdb
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

  jpa:
    open-in-view: true
    show-sql: true
    properties.hibernate:
      format_sql: true

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

#    registerWithEureka: false
#    fetchRegistry: false

